---
title: "untitle"
author: ""
date: "`r Sys.Date()`"
output:
 html_document:
    css : R_style.css
    # theme: cosmo
    highlight: haddock     # Rスクリプトのハイライト形式
    code_folding: 'hide'  # Rコードの折りたたみ表示を設定
    toc: TRUE
    toc_depth: 3           # 見出しの表示とその深さを指定
    toc_float: true        # 見出しを横に表示し続ける
    number_sections: true # 見出しごとに番号を振る
    df_print: paged        # head()の出力をnotebook的なものに（tibbleと相性良）
    latex_engine: xelatex  # zxjatypeパッケージを使用するために変更
    # fig_height: 4.5          # 画像サイズのデフォルトを設定
    # fig_width: 8           # 画像サイズのデフォルトを設定
    dev: png
classoption: xelatex,ja=standard
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())

path <- getwd()

pacman::p_load(tidyverse,patchwork)

# Font for windows and mac
if (path == "D:/Dropbox/2020COVID_impact_R/R"){ 
  theme_set(theme_gray(base_size = 10, base_family = "Arial"))        # Windows用¥
 } else{
  theme_set(theme_gray(base_size = 10, base_family = "HiraginoSans-W3"))  # macOS用
 }
```

```{r}
df <- readr::read_csv("df_google.csv")
```

# 関数の読み込み
```{r}
source("functions.R")
```

# Panic
```{r}
DID_results <-DID(outcome_var = df$Panic)

results_Panic <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Panic)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)
  
graph_Panic <- event_study_graph(data)
```

# Suicide
```{r}
DID_results <-DID(outcome_var = df$Suicide)

results_Suicide <- DID_results 
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Suicide)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Suicide <- event_study_graph(data)
```

# Wellbing
```{r}
DID_results <-DID(outcome_var = df$Wellbing)

results_Wellbing <- DID_results  
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Wellbing)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Wellbing <- event_study_graph(data)
```

# Worry
```{r}
DID_results <-DID(outcome_var = df$Worry)

results_Worry <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Worry)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Worry <- event_study_graph(data)
```

# Boredom
```{r}
DID_results <-DID(outcome_var = df$Boredom)

results_Boredom <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Boredom)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Boredom <- event_study_graph(data)
```

# Contentment 
```{r}
DID_results <-DID(outcome_var = df$Contentment )

results_Contentment <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Contentment )

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Contentment  <- event_study_graph(data)
```

# Divorce
```{r}
DID_results <-DID(outcome_var = df$Divorce)

results_Divorce <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Divorce)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Divorce <- event_study_graph(data)
```

# Impairment
```{r}
DID_results <-DID(outcome_var = df$Impairment)

results_Impairment <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Impairment)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Impairment <- event_study_graph(data)
```

# Loneliness
```{r}
DID_results <-DID(outcome_var = df$Loneliness)

results_Loneliness <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Loneliness)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Loneliness <- event_study_graph(data)
```

# Sadness
```{r}
DID_results <-DID(outcome_var = df$Sadness)

results_Sadness <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Sadness)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Sadness <- event_study_graph(data)
```

# Sleep 
```{r}
DID_results <-DID(outcome_var = df$Sleep )

results_Sleep  <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Sleep )

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Sleep  <- event_study_graph(data)
```

# Stress
```{r}
DID_results <-DID(outcome_var = df$Stress)

results_Stress <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Stress)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Stress <- event_study_graph(data)
```

# Irritability 
```{r}
DID_results <-DID(outcome_var = df$Irritability)

results_Irritability  <- DID_results
```

```{r}
DID_results <- dynamic_DID(outcome_var = df$Irritability)

data <- DID_coefficients_main(DID_results)

data$week <- as.numeric(data$week)

graph_Irritability <- event_study_graph(data)
```


### Graph
```{r}
graph_Panic <- graph_Panic + 
  labs(title = "(a) Panic")

graph_Suicide <- graph_Suicide + 
  labs(title = "(b) Suicide") 

graph_Wellbing <- graph_Wellbing + 
  labs(title = "(c) Wellbing") 

graph_Worry <- graph_Worry + 
  labs(title = "(d) Worry") 

graph <- graph_Panic+graph_Suicide+
   graph_Wellbing+ graph_Worry+plot_layout(ncol = 2)

graph
#保存
ggsave(file = "graph_a.pdf", plot = graph, width = 12, height = 10)

```

```{r}
graph_Boredom <- graph_Boredom + 
  labs(title = "(e) Boredom") 

graph_Contentment <- graph_Contentment + 
  labs(title = "(f) Contentment") 

graph_Divorce <- graph_Divorce + 
  labs(title = "(g) Divorce")

graph_Impairment <- graph_Impairment + 
  labs(title = "(h) Impairment") 

graph <- graph_Boredom + graph_Contentment +
  graph_Divorce + graph_Impairment +plot_layout(ncol = 2)
  
graph

#保存
ggsave(file = "graph_b.pdf", plot = graph,  width = 12, height = 10)
```

```{r}
graph_Loneliness <- graph_Loneliness + 
  labs(title = "(i) Loneliness") 

graph_Sadness <- graph_Sadness + 
  labs(title = "(j) Sadness") 

graph_Sleep <- graph_Sleep + 
  labs(title = "(k) Sleep") 

graph_Stress <- graph_Stress + 
  labs(title = "(l) Stress") 

graph_Irritability <- graph_Irritability + 
  labs(title = "(m) Irritability") 

graph <- graph_Loneliness+graph_Sadness + 
  graph_Sleep+ graph_Stress +
  graph_Irritability +plot_layout(ncol = 2)

graph

#保存
ggsave(file = "graph_c.pdf", plot = graph, width = 12, height = 10)
```


```{r}
table_results_MONTH <- list()
table_results_MONTH[["Boredom"]] <- results_Boredom
table_results_MONTH[["Contentment"]] <- results_Contentment
table_results_MONTH[["Divorce"]] <- results_Divorce 
table_results_MONTH[["Impairment"]] <- results_Impairment

modelsummary::modelsummary(table_results_MONTH,
  gof_omit = "(R2 Adj.|Sample size)",
  output = "latex") 
```

```{r}
table_results_MONTH <- list()
table_results_MONTH[["Irritability"]] <- results_Irritability
table_results_MONTH[["Loneliness"]] <- results_Loneliness
table_results_MONTH[["Panic"]] <- results_Panic
table_results_MONTH[["Sadness"]] <- results_Sadness 


modelsummary::modelsummary(table_results_MONTH,
  gof_omit = "(R2 Adj.|Sample size)",
  output = "latex") 
```


```{r}
table_results_MONTH <- list()
table_results_MONTH[["Sleep"]] <- results_Sleep
table_results_MONTH[["Stress"]] <- results_Stress
table_results_MONTH[["Suicide"]] <- results_Suicide
table_results_MONTH[["Wellbing"]] <- results_Wellbing
table_results_MONTH[["Worry"]] <- results_Worry

modelsummary::modelsummary(table_results_MONTH,
  gof_omit = "(R2 Adj.|Sample size)",
  output = "latex") 
```


```{r}
estimate <- c(results_Boredom$coefficients[["Year:Treatment"]],results_Divorce$coefficients[["Year:Treatment"]],
              results_Contentment$coefficients[["Year:Treatment"]],results_Impairment$coefficients[["Year:Treatment"]],
              results_Irritability$coefficients[["Year:Treatment"]],results_Loneliness$coefficients[["Year:Treatment"]],
              results_Panic$coefficients[["Year:Treatment"]],results_Sadness$coefficients[["Year:Treatment"]],
              results_Sleep$coefficients[["Year:Treatment"]],results_Stress$coefficients[["Year:Treatment"]],
              results_Suicide$coefficients[["Year:Treatment"]],results_Wellbing$coefficients[["Year:Treatment"]],
              results_Worry$coefficients[["Year:Treatment"]])

ci_low <- c(results_Boredom$conf.low[["Year:Treatment"]],results_Divorce$conf.low[["Year:Treatment"]],
            results_Contentment$conf.low[["Year:Treatment"]],results_Impairment$conf.low[["Year:Treatment"]],
            results_Irritability$conf.low[["Year:Treatment"]],results_Loneliness$conf.low[["Year:Treatment"]],
            results_Panic$conf.low[["Year:Treatment"]],results_Sadness$conf.low[["Year:Treatment"]],
            results_Sleep$conf.low[["Year:Treatment"]],results_Stress$conf.low[["Year:Treatment"]],
            results_Suicide$conf.low[["Year:Treatment"]],results_Wellbing$conf.low[["Year:Treatment"]],
            results_Worry$conf.low[["Year:Treatment"]])

ci_high <- c(results_Boredom$conf.high[["Year:Treatment"]],results_Divorce$conf.high[["Year:Treatment"]],
             results_Contentment$conf.high[["Year:Treatment"]],results_Impairment$conf.high[["Year:Treatment"]],
             results_Irritability$conf.high[["Year:Treatment"]],results_Loneliness$conf.high[["Year:Treatment"]],
             results_Panic$conf.high[["Year:Treatment"]],results_Sadness$conf.high[["Year:Treatment"]],
             results_Sleep$conf.high[["Year:Treatment"]],results_Stress$conf.high[["Year:Treatment"]],
             results_Suicide$conf.high[["Year:Treatment"]],results_Wellbing$conf.high[["Year:Treatment"]],
             results_Worry$conf.high[["Year:Treatment"]])

type <- c("Boredom", "Divorce", "Contentment","Impairment","Irritability", "Loneliness", "Panic","Sadness","Sleep", "Stress","Suicide", "Wellbing", "Worry")

df1 <- as.data.frame(list(estimate = estimate, ci_low = ci_low, ci_high= ci_high, type = type))
```

```{r}
plot<-df1 %>% ggplot(aes(x = type, y=estimate, fill=type))+ # データ、x軸、y軸、何で分けるかを宣言
 geom_bar(stat="identity", position="dodge")+ # x軸もy軸も値を指定、積み上げずに横に配置
 geom_errorbar(aes(ymin= ci_low, ymax=ci_high), position=position_dodge(0.9), width=0.2) +
 theme_classic() +
  scale_fill_discrete(guide="none")+
  theme(text = element_text(size = 24))+
coord_flip()
plot

ggsave(file = "did.pdf", plot = plot, width = 8, height = 10)
```

